stages:
- tests
- release

tests:
  image: ubuntu:bionic-20200219
  stage: tests
  only:
    - master
    - helder.tests
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - BLENDER_MAJOR=2.83
    - BLENDER_VERSION=2.83
    - apt update && \
      apt install -y \
        npm \
        curl \
        bzip2 \
        libfreetype6 \
        libgl1-mesa-dev \
        libglu1-mesa \
        libxi6 \
        libxrender1 \
        snap && \
      apt-get -y autoremove && \
      rm -rf /var/lib/apt/lists/*
    - BLENDER_URL=https://download.blender.org/release/Blender$BLENDER_MAJOR/blender-$BLENDER_VERSION-linux-glibc217-x86_64.tar.bz2
    - echo "Installing Blender 2.${BLENDER28_VERSION}"
    - snap install blender --channel=2.83/stable --classic
    - cp -r /builds/real2u/blender2u/ /usr/local/blender/2.8*/scripts/addons
  script:
    - blender -b -P tests/install.py

release:
  image: node:13
  stage: release
  only:
    - master
  script:
    - ls .
    - bash tag.sh